### ISSUE TITLE
Bug when trying to prune

### ISSUE THREAD

**Issue by CanKeles5** [mohaimenz/acdnet#5]
I am running the training with the provided commands. When I try running pruning, I get the following error. I didnt change any of the code

`Traceback (most recent call last):
  File "C:\Users\canke\OneDrive\Desktop\acdnet\torch\pruning.py", line 84, in <module>
    wpt.PruneAndTrain();
  File "C:\Users\canke\OneDrive\Desktop\acdnet\torch\pruning\weight_pruning.py", line 70, in PruneAndTrain
    val_acc, val_loss = self.__validate(net, loss_func);
  File "C:\Users\canke\OneDrive\Desktop\acdnet\torch\pruning\weight_pruning.py", line 158, in __validate
    scores = net(x);
  File "C:\Users\canke\miniconda3\envs\acdnet\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\canke\OneDrive\Desktop\acdnet\torch\resources\models.py", line 92, in forward
    x = self.tfeb(x);
  File "C:\Users\canke\miniconda3\envs\acdnet\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\canke\miniconda3\envs\acdnet\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Users\canke\miniconda3\envs\acdnet\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\canke\miniconda3\envs\acdnet\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\canke\miniconda3\envs\acdnet\lib\site-packages\torch\nn\functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (60x100 and 50x50)`

**Comment by mohaimenz** [comment]
This should not happen if you have the input shape correct. Anyways, could you please send the reproducing steps for this error?
